# Generated by Django 2.1.7 on 2019-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector_app', '0004_auto_20190409_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_data',
            old_name='status',
            new_name='important',
        ),
    ]
