# Generated by Django 2.1.7 on 2019-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector_app', '0005_auto_20190410_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_data',
            name='important',
            field=models.BooleanField(),
        ),
    ]
