# Generated by Django 2.1.7 on 2019-05-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector_app', '0006_auto_20190410_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_data',
            name='owener',
        ),
        migrations.DeleteModel(
            name='Todo_data',
        ),
    ]
