# Generated by Django 2.1.7 on 2019-04-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_registration',
        ),
    ]
